language: java

services:
  - mongodb

cache:
  directories:
    - $HOME/.m2

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version
  - mongod --version

script:
  - mvn verify -Pautodeps,play13 --update-snapshots --settings .travis.settings.xml -e

jdk: oraclejdk7
