language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.embedmongo

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version
  -  mongod --version

script:
  - mvn verify -Pautodeps,play13,xxxembedmongo --update-snapshots --settings .travis.settings.xml -e

jdk: oraclejdk7
